apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-filmes
spec:
  replicas: 2
  minReadySeconds: 60
  selector:
    matchLabels:
      app: web-filmes
  template:
    metadata:
      labels:
        app: web-filmes
    spec:
      containers:
      - name: web
        image: sandovalcp/filmes:v1
        resources: {}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-filmes
spec:
  selector:
    app: web-filmes
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filmes
spec:
  replicas: 3
  minReadySeconds: 60
  selector:
    matchLabels:
      app: filmes
  template:
    metadata:
      labels:
        app: filmes
    spec:
      containers:
      - name: web
        image: mongo
        resources: {}
        ports:
        - containerPort: 80
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: web-green
#spec:
#  selector:
#    app: web-green
#  ports:
#  - port: 80
#    targetPort: 80
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: web
        image: nginx
        resources: {}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
